"""Project-wide constants."""

API_BASE_URL = "https://api.notion.com/v1"
DEFAULT_NOTION_VERSION = "2026-03-11"
DEFAULT_DATABASE_TITLE = "Trade Journal"
DEFAULT_DAILY_RESULTS_TITLE = "Daily Results"
DEFAULT_TIMEZONE = "America/New_York"
DEFAULT_SUPABASE_TRADES_TABLE = "trade_journal_trades"
DEFAULT_DASHBOARD_HOST = "127.0.0.1"
DEFAULT_DASHBOARD_PORT = 8765
MAX_RICH_TEXT_CHUNK_LENGTH = 2000
MAX_SINGLE_PART_UPLOAD_BYTES = 20 * 1024 * 1024
SCREENSHOT_PROPERTY_NAME = "Screenshot"
